# --- Taps ---
tap "homebrew/cask-fonts"
tap "FelixKratz/formulae"

# --- Terminal Tools ---
brew "yazi"
brew "ffmpeg"
brew "sevenzip"
brew "jq"
brew "poppler"
brew "fd"
brew "ripgrep"
brew "fzf"
brew "zoxide"
brew "resvg"
brew "imagemagick"
brew "font-symbols-only-nerd-font"
brew "eza"
brew "lazygit"
brew "neovim"
brew "bat"
brew "carapace"
brew "television"
brew "starship"
brew "btop"
brew "zellij"
brew "mise"

# --- Kubernetes ---
brew "kubectl"
brew "derailed/k9s/k9s"
brew "kubescape"
brew "helm"
brew "siderolabs/tap/talosctl"

# --- GUI apps (casks) ---
cask "ghostty"
cask "zed"
cask "nikitabobko/tap/aerospace"

# --- Fonts ---
cask "font-jetbrains-mono"

# --- Mac App Store apps (optional) ---
brew "mas"

mas "Slack", id: 803453959
